project:
  type: website

website:
  title: "Anish Deshpande"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto