project:
  type: website
  output-dir: ../_site
  resources:
    - PDFs
    - Images_and_Attachments

website:
  title: "Anish Deshpande"
  navbar:
    right:
      - href: Code/index.qmd
        text: Home
      - href: Code/projects.qmd
        text: Projects
      - href: Code/other.qmd
        text: Other

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto